# max cap to test

CPU_PERCENTAGE_CAP=80
RAM_PERCENTAGE_CAP=80
DISK_PERCENTAGE_CAP=80
TEMP_PERCENTAGE_CAP=80

# time threshold in seconds to test

CPU_CHECK_TIMEFRAME=60
RAM_CHECK_TIMEFRAME=60
DISK_CHECK_TIMEFRAME=60
TEMP_CHECK_TIMEFRAME=60

# number of times to test

CPU_CHECK_COUNTER=10
RAM_CHECK_COUNTER=10
DISK_CHECK_COUNTER=10
TEMP_CHECK_COUNTER=10
